$kind: http-request
name: 'PUT products'
method: PUT
url: 'ruhvi.vercel.app/external/products'
order: 38000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {}
