$kind: http-request
name: 'POST products'
method: POST
url: 'ruhvi.vercel.app/external/products'
order: 37000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {}
