import { AgentNode } from './types';

export const INITIAL_AI_HIERARCHY: AgentNode[] = [
  // -------------------------------------------------------------------------
  // APEX NODE: AI Co-Founder
  // -------------------------------------------------------------------------
  {
    id: 'co_founder',
    name: 'Ruhvi AI Co-Founder',
    title: 'Apex Autonomous Business Advisor & Strategic Orchestrator',
    level: 'apex_co_founder',
    category: 'Strategic Brain',
    color: '#f59e0b',
    accentColor: '#fbbf24',
    dotCount: 220,
    radius: 38,
    orbitRadius: 0,
    orbitSpeed: 0,
    orbitAngle: 0,
    orbitElevation: 0,
    state: 'thinking',
    telemetry: {
      latencyMs: 142,
      tokensPerSec: 68.4,
      computeLoadPct: 24,
      activeTool: 'dispatcher.routeIntent()',
      activeModel: 'Gemini 2.5 Pro / GPT-4o Multi-Provider Router',
      autonomyLevel: 'Autonomous',
      currentAction: 'Orchestrating 12 autonomous workers and reviewing growth telemetry...',
      progressPct: 78,
      logLines: [
        { timestamp: '13:58:10', level: 'info', message: 'Apex Orchestrator initialized with Supabase multi-agent bridge.' },
        { timestamp: '13:58:12', level: 'exec', message: 'Signal radar active: Monitoring gross margin, cart dropoff, and keyword surges.' },
        { timestamp: '13:58:15', level: 'success', message: 'Worker 2 (Marketing) dispatched with 22K Gold Choker two-clip campaign directive.' },
      ],
    },
    capabilities: [
      'Multi-Agent Swarm Orchestration',
      'Strategic Business & Revenue Optimization',
      'Realtime Voice WebRTC Synthesis',
      'Autonomous Task & Action Plan Decomposition',
    ],
    subagentIds: [
      'worker_1', 'worker_2', 'worker_3', 'worker_4', 'worker_5', 'worker_6',
      'worker_7', 'worker_8', 'worker_9', 'worker_10', 'worker_11', 'worker_12',
    ],
  },

  // -------------------------------------------------------------------------
  // LEVEL 1: THE 12 CORE WORKERS
  // -------------------------------------------------------------------------
  {
    id: 'worker_1',
    name: 'Worker 1: Analytics',
    title: 'Financial & E-commerce Intelligence Specialist',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Financial Intel',
    color: '#38bdf8',
    accentColor: '#7dd3fc',
    dotCount: 80,
    radius: 20,
    orbitRadius: 170,
    orbitSpeed: 0.003,
    orbitAngle: 0,
    orbitElevation: -15,
    state: 'analyzing',
    telemetry: {
      latencyMs: 95,
      tokensPerSec: 54.2,
      computeLoadPct: 32,
      activeTool: 'supabase.queryOrders()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'Calculating AOV ₹3,850 and cohort repurchase trajectory...',
      progressPct: 65,
      logLines: [
        { timestamp: '13:57:40', level: 'info', message: 'Aggregating last 30-day transaction logs.' },
        { timestamp: '13:57:42', level: 'exec', message: 'Detected 18.4% uptick in 22K Gold category orders.' },
      ],
    },
    capabilities: ['AOV & CLV Modeling', 'Cohort Retention', 'Financial Unit Economics'],
  },
  {
    id: 'worker_2',
    name: 'Worker 2: Marketing',
    title: 'Growth Engine & Creative Campaign Director',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Growth & Ads',
    color: '#f59e0b',
    accentColor: '#fbbf24',
    dotCount: 110,
    radius: 26,
    orbitRadius: 210,
    orbitSpeed: 0.0025,
    orbitAngle: Math.PI / 6,
    orbitElevation: 25,
    state: 'executing',
    telemetry: {
      latencyMs: 120,
      tokensPerSec: 72.1,
      computeLoadPct: 58,
      activeTool: 'co_worker_router.execute()',
      activeModel: 'Gemini 2.5 Pro',
      autonomyLevel: 'Approval Required',
      currentAction: 'Coordinating 3 active Co-Workers for two-video continuous ad pipeline...',
      progressPct: 82,
      logLines: [
        { timestamp: '13:58:01', level: 'info', message: 'Triggered Strategy Co-Worker for cultural positioning angles.' },
        { timestamp: '13:58:04', level: 'exec', message: 'Dispatched Creative Media Co-Worker for Veo/Flow prompts.' },
        { timestamp: '13:58:08', level: 'exec', message: 'Prepared Draft Meta Campaign in PAUSED status with ₹1,800 budget.' },
      ],
    },
    capabilities: ['Campaign Strategy', 'Continuous Video Generation', 'Safe Ads Drafting'],
    subagentIds: ['coworker_strategy', 'coworker_creative', 'coworker_ads', 'coworker_social', 'coworker_email', 'coworker_influencer'],
  },
  {
    id: 'worker_3',
    name: 'Worker 3: SEO',
    title: 'Search Dominance & Organic Traffic Architect',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Organic Growth',
    color: '#10b981',
    accentColor: '#34d399',
    dotCount: 75,
    radius: 19,
    orbitRadius: 180,
    orbitSpeed: 0.0028,
    orbitAngle: (2 * Math.PI) / 6,
    orbitElevation: -30,
    state: 'idle',
    telemetry: {
      latencyMs: 82,
      tokensPerSec: 48.0,
      computeLoadPct: 12,
      activeTool: 'google.searchConsoleAudit()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'Monitoring rank #1 for "anti-tarnish 22k gold jewellery"...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:50:00', level: 'info', message: 'Sitemap crawler refreshed. All product canonicals valid.' },
      ],
    },
    capabilities: ['Structured Schema Injection', 'Search Console Auditing', 'Keyword Mapping'],
  },
  {
    id: 'worker_4',
    name: 'Worker 4: Product',
    title: 'Catalog Discovery, Merchandising & Attribute Optimizer',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Merchandising',
    color: '#a855f7',
    accentColor: '#c084fc',
    dotCount: 75,
    radius: 19,
    orbitRadius: 195,
    orbitSpeed: 0.0022,
    orbitAngle: (3 * Math.PI) / 6,
    orbitElevation: 18,
    state: 'idle',
    telemetry: {
      latencyMs: 90,
      tokensPerSec: 51.5,
      computeLoadPct: 14,
      activeTool: 'catalog.enrichAttributes()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'Catalog indexing synced with Supabase products table...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:52:12', level: 'info', message: 'Enriched 48 SKUs with nano-coating durability tags.' },
      ],
    },
    capabilities: ['Attribute Enrichment', 'Visual Catalog Optimization', 'Bundle Recommendation'],
  },
  {
    id: 'worker_5',
    name: 'Worker 5: Competitor Radar',
    title: 'Market Intelligence & Competitive Pricing Auditor',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Market Intel',
    color: '#ec4899',
    accentColor: '#f472b6',
    dotCount: 75,
    radius: 19,
    orbitRadius: 175,
    orbitSpeed: 0.0031,
    orbitAngle: (4 * Math.PI) / 6,
    orbitElevation: -10,
    state: 'analyzing',
    telemetry: {
      latencyMs: 140,
      tokensPerSec: 62.0,
      computeLoadPct: 29,
      activeTool: 'playwright.auditCompetitor()',
      activeModel: 'Gemini 2.5 Pro',
      autonomyLevel: 'Autonomous',
      currentAction: 'Scanning Giva & Mia by Tanishq 22K festive promotional pricing...',
      progressPct: 52,
      logLines: [
        { timestamp: '13:56:02', level: 'exec', message: 'Giva launching 15% Durga Puja discount campaign.' },
        { timestamp: '13:56:09', level: 'info', message: 'Ruhvi price elasticity advantage: +12% on anti-tarnish warranty.' },
      ],
    },
    capabilities: ['Playwright Competitor Scraping', 'Price Elasticity Tracking', 'Feature Matrix Comparison'],
  },
  {
    id: 'worker_6',
    name: 'Worker 6: Sales & Conversion',
    title: 'Funnel Optimization, Dynamic Bundles & CRO Specialist',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Conversion',
    color: '#6366f1',
    accentColor: '#818cf8',
    dotCount: 75,
    radius: 19,
    orbitRadius: 200,
    orbitSpeed: 0.0026,
    orbitAngle: (5 * Math.PI) / 6,
    orbitElevation: 22,
    state: 'idle',
    telemetry: {
      latencyMs: 88,
      tokensPerSec: 50.0,
      computeLoadPct: 15,
      activeTool: 'cro.optimizeCheckout()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'One-click checkout conversion rate stable at 4.2%...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:45:10', level: 'info', message: 'Post-purchase upsell bundle conversion +8.3%.' },
      ],
    },
    capabilities: ['Funnel Drop-off Diagnostic', 'Dynamic Bundle Engine', 'Checkout Acceleration'],
  },
  {
    id: 'worker_7',
    name: 'Worker 7: Support & Delight',
    title: 'Customer Experience, CX AI & Post-Purchase Resolution',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Customer Delight',
    color: '#14b8a6',
    accentColor: '#2dd4bf',
    dotCount: 75,
    radius: 19,
    orbitRadius: 185,
    orbitSpeed: 0.0029,
    orbitAngle: Math.PI,
    orbitElevation: -20,
    state: 'idle',
    telemetry: {
      latencyMs: 76,
      tokensPerSec: 46.8,
      computeLoadPct: 11,
      activeTool: 'support.triageTickets()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'Zero pending escalation tickets. Customer CSAT: 4.9/5...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:40:00', level: 'info', message: 'Auto-resolved 14 tracking status inquiries via WhatsApp.' },
      ],
    },
    capabilities: ['Automated Triage', 'CSAT Sentiment Tracking', 'Warranty Claim Verification'],
  },
  {
    id: 'worker_8',
    name: 'Worker 8: Content & Copy',
    title: 'Multilingual Brand Storyteller & Copywriting Engine',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Brand Content',
    color: '#f97316',
    accentColor: '#fb923c',
    dotCount: 75,
    radius: 19,
    orbitRadius: 215,
    orbitSpeed: 0.0024,
    orbitAngle: (7 * Math.PI) / 6,
    orbitElevation: 28,
    state: 'generating',
    telemetry: {
      latencyMs: 115,
      tokensPerSec: 64.0,
      computeLoadPct: 41,
      activeTool: 'content.synthesizeMultilingual()',
      activeModel: 'Gemini 2.5 Pro',
      autonomyLevel: 'Autonomous',
      currentAction: 'Drafting colloquial Bengali and Hinglish micro-copy for bridal landing page...',
      progressPct: 70,
      logLines: [
        { timestamp: '13:55:18', level: 'exec', message: 'Phonetic Banglish voiceover transcription completed.' },
      ],
    },
    capabilities: ['Bengali/Hindi Cultural Localization', 'High-Converting Hooks', 'Blog & Editorial Generation'],
  },
  {
    id: 'worker_9',
    name: 'Worker 9: Inventory & Supply',
    title: 'Safety Stock, Reorder Point & Vendor Intelligence',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Supply Chain',
    color: '#84cc16',
    accentColor: '#a3e635',
    dotCount: 75,
    radius: 19,
    orbitRadius: 170,
    orbitSpeed: 0.0033,
    orbitAngle: (8 * Math.PI) / 6,
    orbitElevation: -14,
    state: 'idle',
    telemetry: {
      latencyMs: 84,
      tokensPerSec: 49.2,
      computeLoadPct: 16,
      activeTool: 'inventory.forecastVelocity()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'Stock velocity balanced. 18 days of supply for gold pendants...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:42:00', level: 'info', message: 'All reorder thresholds evaluated against vendor lead times.' },
      ],
    },
    capabilities: ['Stockout Risk Detection', 'Lead-Time Optimization', 'Holding Cost Minimization'],
  },
  {
    id: 'worker_10',
    name: 'Worker 10: Review & Proof',
    title: 'Customer Reviews, UGC Curation & Trust Architect',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Trust & UGC',
    color: '#eab308',
    accentColor: '#fde047',
    dotCount: 75,
    radius: 19,
    orbitRadius: 190,
    orbitSpeed: 0.0027,
    orbitAngle: (9 * Math.PI) / 6,
    orbitElevation: 12,
    state: 'idle',
    telemetry: {
      latencyMs: 79,
      tokensPerSec: 47.0,
      computeLoadPct: 13,
      activeTool: 'reviews.aggregateSentiment()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'Curating 5-star customer unboxing photos for homepage social proof...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:38:00', level: 'info', message: '98.2% positive sentiment across 320 verified buyer reviews.' },
      ],
    },
    capabilities: ['UGC Photo Moderation', 'Structured Review Schema', 'Verified Buyer Badging'],
  },
  {
    id: 'worker_11',
    name: 'Worker 11: Task Execution',
    title: 'Autonomous System Execution & Task Manager Integrator',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'Execution',
    color: '#06b6d4',
    accentColor: '#22d3ee',
    dotCount: 80,
    radius: 20,
    orbitRadius: 205,
    orbitSpeed: 0.0025,
    orbitAngle: (10 * Math.PI) / 6,
    orbitElevation: -24,
    state: 'executing',
    telemetry: {
      latencyMs: 110,
      tokensPerSec: 61.2,
      computeLoadPct: 45,
      activeTool: 'taskManager.createSubTasks()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'Executing database sync and syncing automated project tasks...',
      progressPct: 90,
      logLines: [
        { timestamp: '13:56:40', level: 'exec', message: 'Dispatched 3 background tasks to internal executor queue.' },
      ],
    },
    capabilities: ['Task Decomposition', 'Migration Synchronization', 'Cron & Background Worker Execution'],
  },
  {
    id: 'worker_12',
    name: 'Worker 12: Monitoring',
    title: 'System Health, Security Auditing & Uptime Sentinel',
    level: 'core_worker',
    parentId: 'co_founder',
    category: 'System Health',
    color: '#ef4444',
    accentColor: '#f87171',
    dotCount: 75,
    radius: 19,
    orbitRadius: 180,
    orbitSpeed: 0.003,
    orbitAngle: (11 * Math.PI) / 6,
    orbitElevation: 16,
    state: 'idle',
    telemetry: {
      latencyMs: 65,
      tokensPerSec: 42.0,
      computeLoadPct: 8,
      activeTool: 'health.probeEndpoints()',
      activeModel: 'Gemini 2.5 Flash',
      autonomyLevel: 'Autonomous',
      currentAction: 'All endpoints 100% operational. Average latency: 42ms...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:58:20', level: 'info', message: 'Postgres connection pool healthy. Cloudinary io1kkukg ready.' },
      ],
    },
    capabilities: ['API Latency Probing', 'Security Policy Auditing', 'Integrations Health Monitor'],
  },

  // -------------------------------------------------------------------------
  // LEVEL 2: SPECIALIZED CO-WORKERS (Under Worker 2 Marketing)
  // -------------------------------------------------------------------------
  {
    id: 'coworker_strategy',
    name: 'Strategy Co-Worker',
    title: 'Target Audience, Positioning & Budget Formulator',
    level: 'co_worker',
    parentId: 'worker_2',
    category: 'Marketing Co-Worker (ENABLED)',
    color: '#f59e0b',
    accentColor: '#fbbf24',
    dotCount: 50,
    radius: 14,
    orbitRadius: 48,
    orbitSpeed: 0.009,
    orbitAngle: 0,
    orbitElevation: 8,
    state: 'executing',
    telemetry: {
      latencyMs: 98,
      tokensPerSec: 58.0,
      computeLoadPct: 40,
      activeTool: 'strategy.formulateAngles()',
      activeModel: 'Gemini 2.5 Pro',
      autonomyLevel: 'Autonomous',
      currentAction: 'Formulating 3 cultural angles (Durga Puja, Daily Luxury, Tarnish-Free Guarantee)...',
      progressPct: 95,
      logLines: [
        { timestamp: '13:57:00', level: 'exec', message: 'Budget calculated: Suggested daily ₹1,800 INR for Meta Ads.' },
      ],
    },
    capabilities: ['Angle Generation', 'Targeting Formulation', 'Budget Recommendation'],
  },
  {
    id: 'coworker_creative',
    name: 'Creative Media Co-Worker',
    title: 'Two-Video Continuous Flow Prompt Generator & Cloudinary Pipeline',
    level: 'co_worker',
    parentId: 'worker_2',
    category: 'Marketing Co-Worker (ENABLED)',
    color: '#fbbf24',
    accentColor: '#fde68a',
    dotCount: 55,
    radius: 15,
    orbitRadius: 52,
    orbitSpeed: 0.008,
    orbitAngle: (2 * Math.PI) / 3,
    orbitElevation: -10,
    state: 'generating',
    telemetry: {
      latencyMs: 135,
      tokensPerSec: 66.2,
      computeLoadPct: 62,
      activeTool: 'cloudinary.uploadStream(io1kkukg)',
      activeModel: 'Gemini 2.5 Pro',
      autonomyLevel: 'Autonomous',
      currentAction: 'Generating Video 1 & Video 2 match-cut prompts and Bengali/Hindi voiceovers...',
      progressPct: 88,
      logLines: [
        { timestamp: '13:57:30', level: 'exec', message: 'Google Flow anchor instructions generated.' },
        { timestamp: '13:57:45', level: 'info', message: 'Dispatched upload pipeline targeting Cloudinary cloud io1kkukg.' },
      ],
    },
    capabilities: ['Two-Video Flow Prompts', 'Match-Cut Continuity', 'Multilingual Script & Voiceover'],
  },
  {
    id: 'coworker_ads',
    name: 'Ads Execution Co-Worker',
    title: 'Meta Ads Manager Direct Integrator (Safety First & DRAFT Only)',
    level: 'co_worker',
    parentId: 'worker_2',
    category: 'Marketing Co-Worker (ENABLED)',
    color: '#f97316',
    accentColor: '#fdba74',
    dotCount: 50,
    radius: 14,
    orbitRadius: 50,
    orbitSpeed: 0.0085,
    orbitAngle: (4 * Math.PI) / 3,
    orbitElevation: 12,
    state: 'waiting_approval',
    telemetry: {
      latencyMs: 110,
      tokensPerSec: 52.0,
      computeLoadPct: 35,
      activeTool: 'metaAds.registerDraftCampaign()',
      activeModel: 'Gemini 2.5 Pro',
      autonomyLevel: 'Approval Required',
      currentAction: 'Draft campaign created in PAUSED status. Awaiting Founder explicit authorization...',
      progressPct: 100,
      logLines: [
        { timestamp: '13:58:00', level: 'warn', message: 'Strict Gate: No live money spent without explicit founder signature.' },
      ],
    },
    capabilities: ['Meta Graph API Drafting', 'PAUSED Default Enforcer', 'Founder Approval Gatekeeper'],
  },
  {
    id: 'coworker_social',
    name: 'Social Media Co-Worker',
    title: 'Organic Feed, Stories & Carousel Scheduling',
    level: 'co_worker',
    parentId: 'worker_2',
    category: 'Marketing Co-Worker (DISABLED)',
    color: '#78716c',
    accentColor: '#a8a29e',
    dotCount: 30,
    radius: 12,
    orbitRadius: 60,
    orbitSpeed: 0.005,
    orbitAngle: Math.PI / 4,
    orbitElevation: -5,
    state: 'idle',
    telemetry: {
      latencyMs: 0,
      tokensPerSec: 0,
      computeLoadPct: 0,
      autonomyLevel: 'Supervised',
      currentAction: 'Standby mode (Feature Flag disabled by policy).',
      progressPct: 0,
      logLines: [{ timestamp: '13:00:00', level: 'info', message: 'Co-Worker disabled in config.' }],
    },
    capabilities: ['Feed Strategy', 'Organic Hashtags'],
  },
  {
    id: 'coworker_email',
    name: 'Email Co-Worker',
    title: 'Klaviyo/Resend Drip Sequences & Abandoned Cart Recovery',
    level: 'co_worker',
    parentId: 'worker_2',
    category: 'Marketing Co-Worker (DISABLED)',
    color: '#78716c',
    accentColor: '#a8a29e',
    dotCount: 30,
    radius: 12,
    orbitRadius: 62,
    orbitSpeed: 0.0048,
    orbitAngle: (3 * Math.PI) / 4,
    orbitElevation: 6,
    state: 'idle',
    telemetry: {
      latencyMs: 0,
      tokensPerSec: 0,
      computeLoadPct: 0,
      autonomyLevel: 'Supervised',
      currentAction: 'Standby mode (Feature Flag disabled by policy).',
      progressPct: 0,
      logLines: [{ timestamp: '13:00:00', level: 'info', message: 'Co-Worker disabled in config.' }],
    },
    capabilities: ['Email Flows', 'Segment Targeting'],
  },
  {
    id: 'coworker_influencer',
    name: 'Influencer Co-Worker',
    title: 'KOL Outreach, PR Seeding & Creator Tracking',
    level: 'co_worker',
    parentId: 'worker_2',
    category: 'Marketing Co-Worker (DISABLED)',
    color: '#78716c',
    accentColor: '#a8a29e',
    dotCount: 30,
    radius: 12,
    orbitRadius: 64,
    orbitSpeed: 0.0045,
    orbitAngle: (5 * Math.PI) / 4,
    orbitElevation: -8,
    state: 'idle',
    telemetry: {
      latencyMs: 0,
      tokensPerSec: 0,
      computeLoadPct: 0,
      autonomyLevel: 'Supervised',
      currentAction: 'Standby mode (Feature Flag disabled by policy).',
      progressPct: 0,
      logLines: [{ timestamp: '13:00:00', level: 'info', message: 'Co-Worker disabled in config.' }],
    },
    capabilities: ['Creator Discovery', 'PR Seeding Pipeline'],
  },
];
