import { NextResponse } from 'next/server'

export async function POST(req: Request) {
  try {
    const payload = await req.json()
    
    // Supabase payload structure for custom SMS provider
    const { user, sms } = payload
    
    if (!user || !user.phone || !sms || !sms.otp) {
      return NextResponse.json({ error: 'Invalid payload from Supabase' }, { status: 400 })
    }

    const phone = user.phone.replace('+', '') // MSG91 expects without '+'
    const otp = sms.otp
    
    const authKey = process.env.MSG91_AUTH_KEY
    const templateId = process.env.MSG91_TEMPLATE_ID

    if (!authKey || !templateId) {
      console.error('MSG91_AUTH_KEY or MSG91_TEMPLATE_ID is missing in environment variables.')
      return NextResponse.json({ error: 'MSG91 configuration missing' }, { status: 500 })
    }

    // Call MSG91 Send OTP API (passing custom OTP generated by Supabase)
    const msg91Url = `https://control.msg91.com/api/v5/otp?template_id=${templateId}&mobile=${phone}&otp=${otp}`
    
    const response = await fetch(msg91Url, {
      method: 'POST',
      headers: {
        'authkey': authKey,
        'Content-Type': 'application/json'
      },
      // Some versions of MSG91 API expect a body even if parameters are in URL, 
      // but usually the query string is sufficient. We provide an empty body just in case.
      body: JSON.stringify({}) 
    })

    const data = await response.json()

    if (!response.ok || data.type === 'error') {
      console.error('MSG91 Error:', data)
      return NextResponse.json({ error: data.message || 'Failed to send SMS via MSG91' }, { status: 500 })
    }

    return NextResponse.json({ success: true, message: 'SMS sent successfully' }, { status: 200 })

  } catch (error: any) {
    console.error('Webhook error:', error)
    return NextResponse.json({ error: 'Internal Server Error', details: error.message }, { status: 500 })
  }
}
