$kind: http-request
name: 'POST ai/settings'
method: POST
url: 'ruhvi.vercel.app/admin/ai/settings'
order: 17000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {}
