$kind: http-request
name: 'PATCH productivity-config'
method: PATCH
url: 'ruhvi.vercel.app/admin/productivity-config'
order: 54000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {}
