#!/usr/bin/env bash
# ── Ruhvi EspoCRM Extension — Native Install (nginx + php-fpm + MariaDB) ──
# Installs the Ruhvi integration extension into an existing EspoCRM instance
# that was installed natively (not via the docker-compose stack).
#
# Usage:
#   chmod +x install-native.sh
#   sudo ./install-native.sh /path/to/esporcrm
#
# The install dir can be omitted if the script is run from the EspoCRM root
# (the directory that contains app.php / data/config.php / custom/Espo).
#
# Env vars read (all optional; interactive prompt if not provided):
#   RUHVI_BASE_URL      e.g. https://support.ruhvi.in
#   ESPO_WEBHOOK_SECRET shared HMAC secret (must match Vercel env)
#   ESPO_API_KEY        API key from EspoCRM Admin → API Credentials
#
# To run non-interactively (CI / one-shot):
#   sudo RUHVI_BASE_URL=https://support.ruhvi.in \
#        ESPO_WEBHOOK_SECRET=xxx \
#        ESPO_API_KEY=yyy \
#        ./install-native.sh /path/to/esporcrm

set -euo pipefail

# ── 1. Resolve the EspoCRM install directory ───────────────────────────────
if [ -n "${1:-}" ]; then
  INSTALL_DIR="$1"
else
  if [ -f app.php ] && [ -f data/config.php ]; then
    INSTALL_DIR="$(pwd)"
  else
    echo "Usage: $0 /path/to/esporcrm" >&2
    echo "Or run this script from the EspoCRM install root." >&2
    exit 1
  fi
fi

INSTALL_DIR="$(cd "$INSTALL_DIR" && pwd)"

for f in app.php data/config.php custom; do
  if [ ! -e "$INSTALL_DIR/$f" ]; then
    echo "ERROR: '$INSTALL_DIR/$f' not found. Not an EspoCRM install root." >&2
    exit 1
  fi
done

echo "==> EspoCRM install dir: $INSTALL_DIR"

# ── 2. Gather secrets (env var → prompt → skip) ────────────────────────────
read -r -e -p "Ruhvi base URL (e.g. https://support.ruhvi.in) [${RUHVI_BASE_URL:-https://support.ruhvi.in}]: " _input
RUHVI_BASE_URL="${RUHVI_BASE_URL:-${_input:-https://support.ruhvi.in}}"

if [ -n "${ESPO_WEBHOOK_SECRET:-}" ]; then
  echo "Using ESPO_WEBHOOK_SECRET from env."
else
  read -r -s -p "ESPO_WEBHOOK_SECRET (shared HMAC secret, no spaces): " ESPO_WEBHOOK_SECRET
  echo
fi

if [ -n "${ESPO_API_KEY:-}" ]; then
  echo "Using ESPO_API_KEY from env."
else
  read -r -s -p "ESPO_API_KEY (create in Admin → API Credentials first): " ESPO_API_KEY
  echo
fi

if [ -z "$ESPO_WEBHOOK_SECRET" ] || [ -z "$ESPO_API_KEY" ]; then
  echo "WARNING: one or more secrets are empty. The extension will be installed"
  echo "         but webhooks/context will fail until ruhvi-config.php is filled in."
fi

# ── 3. Back up existing Ruhvi custom files ─────────────────────────────────
TS="$(date +%Y%m%d%H%M%S)"
BACKUP_DIR="$INSTALL_DIR/backups/ruhvi-$TS"
mkdir -p "$BACKUP_DIR"
if [ -d "$INSTALL_DIR/custom/Espo/Custom" ]; then
  cp -a "$INSTALL_DIR/custom/Espo/Custom" "$BACKUP_DIR/Custom"
fi
if [ -d "$INSTALL_DIR/client/custom" ]; then
  cp -a "$INSTALL_DIR/client/custom" "$BACKUP_DIR/client-custom"
fi
echo "==> Backed up existing custom dirs to $BACKUP_DIR"

# ── 4. Locate this script's source tree (deploy/esporcrm/ on the VPS) ──────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXT_SRC="$SCRIPT_DIR/extension/Espo"
CLIENT_SRC="$SCRIPT_DIR/client-custom"

if [ ! -d "$EXT_SRC/Custom" ]; then
  echo "ERROR: $EXT_SRC/Custom not found. Run this script from deploy/esporcrm/." >&2
  exit 1
fi

# ── 5. Copy backend extension ──────────────────────────────────────────────
mkdir -p "$INSTALL_DIR/custom/Espo"
cp -a "$EXT_SRC/Custom" "$INSTALL_DIR/custom/Espo/"
echo "==> Backend extension installed: $INSTALL_DIR/custom/Espo/Custom"

# ── 6. Copy frontend custom client ─────────────────────────────────────────
if [ -d "$CLIENT_SRC" ]; then
  mkdir -p "$INSTALL_DIR/client"
  cp -a "$CLIENT_SRC" "$INSTALL_DIR/client/custom"
  echo "==> Frontend custom client installed: $INSTALL_DIR/client/custom"
fi

# ── 7. Write ruhvi-config.php (used by RuhviConfig helper, above getenv) ───
CONFIG_FILE="$INSTALL_DIR/custom/Espo/ruhvi-config.php"
php -r '
$config = [
    "ruhviBaseUrl"      => $argv[1],
    "espoWebhookSecret" => $argv[2],
    "espoApiKey"        => $argv[3],
];
file_put_contents(
    $argv[4],
    "<?php\n// Ruhvi <-> EspoCRM integration config. Generated by install-native.sh on " . date("c") . ".\nreturn " . var_export($config, true) . ";\n"
);
' "$RUHVI_BASE_URL" "$ESPO_WEBHOOK_SECRET" "$ESPO_API_KEY" "$CONFIG_FILE"
chmod 640 "$CONFIG_FILE"
echo "==> Wrote $CONFIG_FILE"

# ── 8. Set ownership to the web server user (www-data typical) ─────────────
WEB_USER="${WEB_USER:-www-data}"
if id "$WEB_USER" &>/dev/null; then
  chown -R "$WEB_USER":"$WEB_USER" "$INSTALL_DIR/custom/Espo" "$INSTALL_DIR/client/custom" "$CONFIG_FILE" 2>/dev/null || true
fi

# ── 9. Rebuild EspoCRM metadata (creates custom fields / panel) ────────────
echo "==> Rebuilding EspoCRM metadata..."
if command -v php >/dev/null 2>&1; then
  if [ -x "$INSTALL_DIR/app.php" ]; then
    (cd "$INSTALL_DIR" && php app.php rebuild)
  else
    echo "WARNING: app.php not executable — run rebuild manually:"
    echo "  cd $INSTALL_DIR && php app.php rebuild"
  fi
else
  echo "WARNING: php not found — run rebuild manually:"
  echo "  cd $INSTALL_DIR && php app.php rebuild"
fi

# ── 10. php-fpm env (optional): also expose vars to the web SAPI ───────────
echo ""
echo "=== Done. Remaining manual steps ==="
echo " 1. EspoCRM Admin → API Credentials → create an API Key (if you haven't),"
echo "    then confirm ESPO_API_KEY in $CONFIG_FILE matches it."
echo " 2. EspoCRM Admin → Entity Manager → Case: verify fields"
echo "    (ruhviTicketId_c, ruhviStatus_c, ruhviCustomerEmail_c, ...) exist."
echo " 3. EspoCRM Admin → Roles: create a 'Ruhvi Support' role for agents"
echo "    with Case/Note access."
echo " 4. Case status options must include: New, Assigned, In Process, Pending,"
echo "    On Hold, Closed, Reopened."
echo " 5. EspoCRM Admin → Settings → set Site URL to https://crm.support.ruhvi.in"
echo "    (currently may be wrong)."
echo " 6. On Vercel set: ESPO_ENABLED=true, ESPO_BASE_URL=https://crm.support.ruhvi.in,"
echo "    ESPO_API_KEY, ESPO_WEBHOOK_SECRET (same values), and deploy the app."
echo ""
echo "Verify: https://crm.support.ruhvi.in/api/v1/HealthCheck should return 200."
